#!/bin/bash

../../../tools/az-auth.sh

RED='\033[0;31m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# ensure gcloud installed
if ! command -v gcloud &> /dev/null
then
    printf "${RED}gcloud is not installed.${NC}\n"
    exit 1
fi

GCLOUD_ACCOUNT=$(gcloud config get-value account)

if [[ -z "$GCLOUD_ACCOUNT" ]]
then
    printf "${RED}gcloud is not authenticated.${NC}\n"
    exit 1
fi

printf "gcloud is authenticated with ${BLUE}${GCLOUD_ACCOUNT}${NC}.\n"
