package com.avaulta.gateway.tokens;

import java.util.function.Function;

public interface DeterministicTokenizationStrategy {



    /**
     * @param originalDatum       to tokenize
     * @param canonicalization
     * @return token (deterministic based on canonically-equivalent originals)
     */
    default byte[] getToken(String originalDatum, Function<String, String> canonicalization) {
        return getToken(canonicalization.apply(originalDatum));
    }

    /**
     * @param originalDatum       to tokenize
     * @return token (deterministic based on canonically-equivalent originals)
     */
    byte[] getToken(String originalDatum);


    /**
     * @return length, in bytes, of tokens generated by this strategy
     *
     * q: too coupled to hash-based implementation?
     */
    int getTokenLength();
}
