SOURCE: dropbox-business
TARGET_HOST: api.dropboxapi.com
SOURCE_AUTH_STRATEGY_IDENTIFIER: oauth2_refresh_token
GRANT_TYPE: refresh_token
IDENTIFIER_SCOPE_ID: dropbox-business
REFRESH_ENDPOINT: https://api.dropboxapi.com/oauth2/token
