SOURCE: gdirectory
SOURCE_AUTH_STRATEGY_IDENTIFIER: gcp_service_account_key
TARGET_HOST: admin.googleapis.com
OAUTH_SCOPES: https://www.googleapis.com/auth/admin.directory.user.readonly https://www.googleapis.com/auth/admin.directory.user.alias.readonly https://www.googleapis.com/auth/admin.directory.domain.readonly https://www.googleapis.com/auth/admin.directory.group.readonly https://www.googleapis.com/auth/admin.directory.group.member.readonly https://www.googleapis.com/auth/admin.directory.orgunit.readonly https://www.googleapis.com/auth/admin.directory.rolemanagement.readonly
IDENTIFIER_SCOPE_ID: gapps
