name: Build - java

# Build Java part of our project as a GitHub action
# see https://help.github.com/en/actions/language-and-framework-guides/building-and-testing-java-with-maven

on:
  workflow_call:
    inputs:
      java-version:
        required: false
        type: string
        description: Java version to use # see https://github.com/actions/setup-java#supported-version-syntax
        default: 17
      java-distribution:
        required: false
        type: string
        description: java distribution to use # see https://github.com/actions/setup-java#supported-distributions
        default: zulu

jobs:
  ci_java:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: ${{ inputs.java-version }}
          # https://github.com/actions/setup-java#supported-distributions
          distribution: zulu
      - name: Compile
        working-directory: java/
        run: |
          mvn clean compile -T 2C -Dversions.logOutput=false -DprocessDependencies=false -DprocessDependencyManagement=false
      - name: Test
        working-directory: java/
        run: |
          mvn post-clean test -T 2C -Dversions.logOutput=false -DprocessDependencies=false -DprocessDependencyManagement=false -Dsurefire.forkCount=2.5C -Dsurefire.reuseForks=true

