name: CI - bundles

# CI for our project as a GitHub action
# see https://help.github.com/en/actions/language-and-framework-guides/building-and-testing-java-with-maven

# refactor to use matrix?
# see https://github.com/actions/setup-java#testing-against-different-java-versions

on:
  push: # mainline + rc's only
    branches:
      - 'main'
      - 'rc-*'
      - 's163-gcp-fix-bulk'

jobs:
  bundle:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        implementation: [ 'gcp', 'aws' ]
    name: bundle ${{ matrix.implementation }}
    steps:
      # apparently need to checkout, even if action you call does it?
      - name: Check out code
        uses: actions/checkout@v4
      - name: Build bundle
        uses: ./.github/workflows/build-bundle.yaml
        with:
         implementation: ${{ matrix.implementation }}
