name: CI - java8

# CI for our project as a GitHub action
# see https://help.github.com/en/actions/language-and-framework-guides/building-and-testing-java-with-maven

on:
  push:
    branches:
      - '**' # should match all branches

jobs:
  ci_java_8:
    uses: ./.github/workflows/build-java.yaml
    with:
      compile-profile: java8
