name: CI - java

# CI for our project as a GitHub action
# see https://help.github.com/en/actions/language-and-framework-guides/building-and-testing-java-with-maven

# refactor to use matrix?
# see https://github.com/actions/setup-java#testing-against-different-java-versions

on:
  push: # mainline + rc's only
    branches:
      - '**' # as of March 2025, I think worth doing for all branches
      - 'main'
      - 'rc-*'

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  # Java 21 - released 19 Sept 2023, supported until Sept 2028 (LTS)
  ci_java21:
    uses: ./.github/workflows/build-java.yaml
    with:
      java-version: '21.0.11'

  # Java 25 - released 17 Oct 2025, supported until Apr 2026
  ci_java25:
    uses: ./.github/workflows/build-java.yaml
    with:
      java-version: '25.0.3'

  # Java 26 - released March 2026
  ci_java26:
    uses: ./.github/workflows/build-java.yaml
    with:
      java-version: '26.0.1'