name: CI - java17 core

# NOTE: as of Dec 2024, regulard build is ALSO java17, so not useful - but let's keep around bc possibly Worklytics will use 17 beyond when that's the proxy default

# CI to build and test project components for which we need java17 builds
# NOTE: this is ONLY core/gateway-core libraries; we don't build the executable/deployment bundles
#      (eg, this does not build, cmd-line,aws, gcp)
#
# see https://help.github.com/en/actions/language-and-framework-guides/building-and-testing-java-with-maven

# Disable for now - hope we can dispense with this soon
on:
  workflow_dispatch: # allow manual triggering

#  push:
#    branches:
#      - '**' # should match all branches

jobs:
  ci_java17_core:
    env:
      # compile-profile: '-P java8 ' # NOTE: trailing space is important
      java-version: '17' # build w java 17, but pom configured to still build java 8 byte code
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: ${{ env.java-version }}
          # https://github.com/actions/setup-java#supported-distributions
          distribution: zulu
      - name: Compile gateway-core
        working-directory: java/gateway-core
        run: |
          mvn package install ${{ env.compile-profile }}-T 2C -Dversions.logOutput=false \
            -DprocessDependencies=false -DprocessDependencyManagement=false
      - name: Test gateway-core
        working-directory: java/gateway-core
        run: |
          mvn post-clean test ${{ env.compile-profile }}-T 2C -Dversions.logOutput=false \
            -DprocessDependencies=false -DprocessDependencyManagement=false  \
            -Dsurefire.forkCount=2.5C -Dsurefire.reuseForks=true
      - name: Compile core
        working-directory: java/core
        run: |
          mvn compile ${{ env.compile-profile }}-T 2C -Dversions.logOutput=false \
            -DprocessDependencies=false -DprocessDependencyManagement=false

# JDK-8 core tests failing after fixes to support JDK-21 (see https://github.com/Worklytics/psoxy/pull/572)
# not bothering to fix for now, as only used as library in linked builds - deploying to jre-8 is not supported
# (and actually it compiles, it's just the tests the fail)
      - name: Test core
        working-directory: java/core
        run: |
          mvn post-clean test ${{ env.compile-profile }}-T 2C -Dversions.logOutput=false \
            -DprocessDependencies=false -DprocessDependencyManagement=false  \
            -Dsurefire.forkCount=2.5C -Dsurefire.reuseForks=true
