name: 'validate Terraform Modules'

on:
  push:
    branches:
      - '**'

jobs:
  validate_tf_modules:
    name: 'validate tf modules'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        terraform_version: [ '~1.6.0', '~1.7.0', '~1.8.0', '~1.9.0', '~1.10.0', '~1.11.0', '~1.12.0', 'latest' ]
        module:
          # Modules that only need validation
          - { name: 'psoxy-constants', test: false }
          # Modules that have tests
          - { name: 'worklytics-connector-specs', test: true }
          - { name: 'gcp-host', test: true }
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: 'setup Terraform'
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ matrix.terraform_version }}

      - name: "Terraform - validate ${{ matrix.module.name }}"
        working-directory: infra/modules/${{ matrix.module.name }}
        run: |
          terraform init -reconfigure
          terraform validate

      - name: "Terraform - test ${{ matrix.module.name }}"
        if: ${{ matrix.module.test }}
        working-directory: infra/modules/${{ matrix.module.name }}
        run: |
          terraform test
