name: CI - Tools

on:
  push:
    branches:
      - '**'

jobs:
  ci_tools:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # 16 is min version recommended to users
        # 18 released 2022-04-19
        # 19 released 2022-10-18
        node-version: [ 19 ]
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: ./tools/psoxy-test
    - name: Install dependencies
      working-directory: ./tools/psoxy-test
      run: npm i
    - name: Run test
      working-directory: ./tools/psoxy-test
      run: npm test
