name: CI - terraform dev examples / modules

on:
  push:
    branches:
      - '**' # should match all branches

jobs:
  validate:
    name: validate
    runs-on: ubuntu-latest
    env:
      TERRAFORM_VERSION: 1.0.8
    steps:
      - name: Check out code
        uses: actions/checkout@v1

      - name: 'setup Terraform'
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: ${{ env.TERRAFORM_VERSION }}
          
      - name: 'Terraform - validate examples-dev/gcp-google-workspace'
        working-directory: infra/examples-dev/gcp-google-workspace
        run: |
          terraform init -reconfigure
          terraform validate

      - name: 'Terraform - validate examples-dev/aws-msft-365'
        working-directory: infra/examples-dev/aws-msft-365
        run: |
          terraform init -reconfigure
          terraform validate
