name: 'validate Terraform Examples against remotes'

# as these examples point to remote Terraform modules, such as a release or rc-, we only want to
# validate them on mainline/rc- branches, otherwise we'd they'd fail irregardless of the branches
# code until the rc- / release on which they depend is fixed
on:
  workflow_dispatch: # to allow manual triggering
  push:
    branches:
      - 'main'

jobs:
  validate_tf_examples_remotes:
    strategy:
      matrix:
        example_path: [
          'examples/gcp-bootstrap-cft',
          'examples/gcp-bootstrap-simple',
        ]
        terraform_version: [ '~1.6.0', '~1.7.0', '~1.8.0', '~1.9.0', '~1.10.0', 'latest' ]
    uses: ./.github/workflows/ci-terraform-example.yaml
    with:
      terraform_version: ${{ matrix.terraform_version }}
      example_path: ${{ matrix.example_path }}
