name: 'validate Terraform Modules'

on:
  push:
    branches:
      - '**'

jobs:
  validate_tf_modules:
    name: 'validate tf modules'
    runs-on: ubuntu-latest
    env:
      TERRAFORM_VERSION: 1.3.9
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: 'setup Terraform'
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: ${{ env.TERRAFORM_VERSION }}

      - name: "Terraform - validate modules/psoxy-constants"
        working-directory: infra/modules/psoxy-constants
        run: |
          terraform init -reconfigure
          terraform validate