name: CI - Tools

on:
  push:
    branches:
      - '**'

jobs:
  ci_tools:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # even numbers are LTS; ods go to ~3m maintenance after next major version
        # 16 is min version recommended to users; but unmaintained since 2023-10
        # 18 released 2022-04-19 - maintained until June 2025
        # 20 maintained until June 2026
        # 21 is latest as of March 2023, with 22 coming in May
        node-version: [ 18, 20, latest]
    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: ./tools/psoxy-test
    - name: Install dependencies
      working-directory: ./tools/psoxy-test
      run: npm i
    - name: Run test
      working-directory: ./tools/psoxy-test
      run: npm test
