name: 'validate Terraform Examples'

on:
  workflow_call:
    inputs:
      example_path:
        required: false
        type: string
        description: Java version to use # see https://github.com/actions/setup-java#supported-version-syntax
        default: 17

jobs:
  validate_tf_examples:
    name: 'validate tf examples'
    runs-on: ubuntu-latest
    env:
      TERRAFORM_VERSION: 1.3.3
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: 'setup Terraform'
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: ${{ env.TERRAFORM_VERSION }}

      - name: "Terraform - validate ${{ inputs.example_path }}"
        working-directory: infra/${{ inputs.example_path }}
        run: |
          terraform init -reconfigure
          terraform validate