name: 'validate Terraform Examples'

on:
  workflow_call:
    inputs:
      example_path:
        required: false
        type: string
        description: Java version to use # see https://github.com/actions/setup-java#supported-version-syntax
        default: 17
      terraform_version:
        required: false
        type: string
        description: Terraform version to use
        default: '~1.6.0'

jobs:
  validate_tf_example:
    name: 'validate tf examples'
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: 'setup Terraform'
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: ${{ inputs.terraform_version }}

      - name: "Terraform - validate ${{ inputs.example_path }}"
        working-directory: infra/${{ inputs.example_path }}
        run: |
          terraform init -reconfigure
          terraform validate
