# trigger this on release publish in future
#on:
#  release:
#    types: [published]

on:
  workflow_call:
    inputs:
      release:
        required: true
        type: string
        description: "release to publish (eg, v0.4.49)"

jobs:
  publish-example-aws:
    uses: ./.github/workflows/publish-example.yaml
    with:
      example-repo: 'Worklytics/psoxy-example-aws'
      example-to-copy: 'infra/examples-dev/aws'
      example-repo-token: ${{ secrets.PSOXY_EXAMPLE_AWS_TOKEN }}
      release: ${{ inputs.release }}
  publish-example-gcp:
    uses: ./.github/workflows/publish-example.yaml
    with:
      example-repo: 'Worklytics/psoxy-example-gcp'
      example-to-copy: 'infra/examples-dev/gcp'
      example-repo-token: ${{ secrets.PSOXY_EXAMPLE_GCP_TOKEN }}
      release: ${{ inputs.release }}
