on:
  workflow_call:
    inputs:
      example_path:
        required: false
        type: string
        description: Path to the example to validate, relative to ./infra/

name: 'terrafrom-sec-analysis'
jobs:
  tfsec:
    name: terrafrom-sec-analysis
    runs-on: ubuntu-latest

    # q: what version of Terraform does this use??

    steps:
      - name: Clone repo
        uses: actions/checkout@v4

        # see: https://github.com/marketplace/actions/aqua-security-trivy#inputs
      - name: Run Trivy vulnerability scanner in IaC mode
        uses: aquasecurity/trivy-action@0.20.0
        working-directory: infra/${{ inputs.example_path }}
        with:
          scan-type: 'config'
          format: 'table'
          hide-progress: true
          scanners: 'config'
          trivyignores: '.trivyignore' # default? omit this?
          tf-vars: .github/workflows/tfvars-examples/${{ inputs.example_path }}.tfvars